GofioScript/config/routes.rb
Rails.application.routes.draw do
  get '/maps/show/:id', to: "maps#show"
  get "/types/loadTypesFromCsv", to: "types#loadTypesFromCsv"
  get "/coffe_shops/loadCoffeShopsFromCsv", to: "coffe_shops#loadCoffeShopsFromCsv"
  get "/attractives/loadAttractivesFromCsv", to: "attractives#loadAttractivesFromCsv"

  get "/attractives/showByTypeId/:id", to: "attractives#showByTypeId"
  resources :coffe_shops
  resources :attractives
  resources :types

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

GofioScript/app/models/attractive.rb
class Attractive < ApplicationRecord
  belongs_to :type
end

GofioScript/app/controllers/attractives_controller.rb
require 'csv'
class AttractivesController < ApplicationController
  before_action :set_attractive, only: [:show, :edit, :update, :destroy]

  def loadAttractivesFromCsv
        csvFile = File.read("atractivos.csv")
        CSV.parse(csvFile, { headers: true, col_sep: "#" }).each do | row |
          currentType = Type.getTypeIdFromType row["TIPO"]
          Attractive.create(name: row["NOMBRE"], description: row["DESCRIPCION"], address: row["DIRECCION"], web: row["WEB"], telephone: row["TELEFONO"], latitude: row["LATITUD"], longitude: row["LONGITUD"], type_id: currentType.id, schedule: row["HORARIO"])
        end
  end

  # GET /attractives
  # GET /attractives.json
  def index
    @attractives = Attractive.all
  end

  # GET /attractives/1
  # GET /attractives/1.json
  def show
  end

  def showByTypeId
    @attractives = Attractive.where(:type_id => params[:id])
  end

  # GET /attractives/new
  def new
    @attractive = Attractive.new
  end

  # GET /attractives/1/edit
  def edit
  end

  # POST /attractives
  # POST /attractives.json
  def create
    @attractive = Attractive.new(attractive_params)

    respond_to do |format|
      if @attractive.save
        format.html { redirect_to @attractive, notice: 'Attractive was successfully created.' }
        format.json { render :show, status: :created, location: @attractive }
      else
        format.html { render :new }
        format.json { render json: @attractive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractives/1
  # PATCH/PUT /attractives/1.json
  def update
    respond_to do |format|
      if @attractive.update(attractive_params)
        format.html { redirect_to @attractive, notice: 'Attractive was successfully updated.' }
        format.json { render :show, status: :ok, location: @attractive }
      else
        format.html { render :edit }
        format.json { render json: @attractive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractives/1
  # DELETE /attractives/1.json
  def destroy
    @attractive.destroy
    respond_to do |format|
      format.html { redirect_to attractives_url, notice: 'Attractive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attractive
      @attractive = Attractive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attractive_params
      params.require(:attractive).permit(:name, :description, :address, :web, :telephone, :latitude, :longitude, :type_id, :schedule)
    end
end

GofioScript/app/helpers/attractives_helper.rb
module AttractivesHelper
end

GofioScript/app/views/attractives/_form.html.erb
<%= form_with(model: attractive, local: true) do |form| %>
  <% if attractive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attractive.errors.count, "error") %> prohibited this attractive from being saved:</h2>

      <ul>
      <% attractive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :web %>
    <%= form.text_field :web %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.text_field :telephone %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.text_field :type_id %>
  </div>

  <div class="field">
    <%= form.label :schedule %>
    <%= form.text_field :schedule %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

GofioScript/app/views/attractives/edit.html.erb
<h1>Editing Attractive</h1>

<%= render 'form', attractive: @attractive %>

<%= link_to 'Show', @attractive %> |
<%= link_to 'Back', attractives_path %>

GofioScript/app/views/attractives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attractives</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Web</th>
      <th>Telephone</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Type</th>
      <th>Schedule</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractives.each do |attractive| %>
      <tr>
        <td><%= attractive.name %></td>
        <td><%= attractive.description %></td>
        <td><%= attractive.address %></td>
        <td><%= attractive.web %></td>
        <td><%= attractive.telephone %></td>
        <td><%= attractive.latitude %></td>
        <td><%= attractive.longitude %></td>
        <td><%= attractive.type %></td>
        <td><%= attractive.schedule %></td>
        <td><%= link_to 'Show', attractive %></td>
        <td><%= link_to 'Edit', edit_attractive_path(attractive) %></td>
        <td><%= link_to 'Destroy', attractive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attractive', new_attractive_path %>

GofioScript/app/views/attractives/loadAttractivesFromCsv.erb
<h1>Finished</h1>

GofioScript/app/views/attractives/new.html.erb
<h1>New Attractive</h1>

<%= render 'form', attractive: @attractive %>

<%= link_to 'Back', attractives_path %>

GofioScript/app/views/attractives/show.html.erb
<p id="notice"><%= notice %></p>
<div class="ml-2 mr-2">
  <p>
    <strong>Name:</strong>
  <p class="text-light"><%= @attractive.name %></p>
  </p>

  <p>
    <strong>Description:</strong>
  <p class="text-light"><%= @attractive.description %></p>
  </p>

  <p>
    <strong>Address:</strong>
  <p class="text-light"><%= @attractive.address %></p>
  </p>
</div>

<a href="/types">Back</a>
<a href="/maps/show/<%= @attractive.id %>">Add</a>

GofioScript/app/views/attractives/showByTypeId.erb
<h3 class="mt-5 text-center">Choose a place</h3><hr>
<div class="mt-2 container bg-light">

  <ul>
    <% @attractives.each do |each| %>
      <li>
        <a href="/attractives/<%= each.id %>"><%= each.name %></a>
      </li>
    <% end %>
  </ul>
</div>

<a href="/types">Back</a>