GofioScript/config/routes.rb
Rails.application.routes.draw do
  get '/maps/show/:id', to: "maps#show"
  get "/types/loadTypesFromCsv", to: "types#loadTypesFromCsv"
  get "/coffe_shops/loadCoffeShopsFromCsv", to: "coffe_shops#loadCoffeShopsFromCsv"
  get "/attractives/loadAttractivesFromCsv", to: "attractives#loadAttractivesFromCsv"

  get "/attractives/showByTypeId/:id", to: "attractives#showByTypeId"
  resources :coffe_shops
  resources :attractives
  resources :types

  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

GofioScript/app/models/coffe_shop.rb
class CoffeShop < ApplicationRecord
end

GofioScript/app/controllers/coffe_shops_controller.rb
require 'csv'
class CoffeShopsController < ApplicationController
  before_action :set_coffe_shop, only: [:show, :edit, :update, :destroy]

  def loadCoffeShopsFromCsv
    csvFile = File.read("coffeeShops.csv")
    CSV.parse(csvFile, { headers: true, col_sep: "#" }).each do | row |
      currentType = Type.getTypeIdFromType row["TIPO"]
      CoffeShop.create(name: row["NOMBRE"], description: row["DESCRIPCION"], latitude: row["LATITUD"], longitude: row["LONGITUD"])
    end
  end
  # GET /coffe_shops
  # GET /coffe_shops.json
  def index
    @coffe_shops = CoffeShop.all
  end

  # GET /coffe_shops/1
  # GET /coffe_shops/1.json
  def show
  end

  # GET /coffe_shops/new
  def new
    @coffe_shop = CoffeShop.new
  end

  # GET /coffe_shops/1/edit
  def edit
  end

  # POST /coffe_shops
  # POST /coffe_shops.json
  def create
    @coffe_shop = CoffeShop.new(coffe_shop_params)

    respond_to do |format|
      if @coffe_shop.save
        format.html { redirect_to @coffe_shop, notice: 'Coffe shop was successfully created.' }
        format.json { render :show, status: :created, location: @coffe_shop }
      else
        format.html { render :new }
        format.json { render json: @coffe_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffe_shops/1
  # PATCH/PUT /coffe_shops/1.json
  def update
    respond_to do |format|
      if @coffe_shop.update(coffe_shop_params)
        format.html { redirect_to @coffe_shop, notice: 'Coffe shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @coffe_shop }
      else
        format.html { render :edit }
        format.json { render json: @coffe_shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffe_shops/1
  # DELETE /coffe_shops/1.json
  def destroy
    @coffe_shop.destroy
    respond_to do |format|
      format.html { redirect_to coffe_shops_url, notice: 'Coffe shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffe_shop
      @coffe_shop = CoffeShop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffe_shop_params
      params.require(:coffe_shop).permit(:name, :description, :latitude, :longitude)
    end
end

GofioScript/app/helpers/coffe_shops_helper.rb
module CoffeShopsHelper
end

GofioScript/app/views/coffe_shops/_form.html.erb
<%= form_with(model: coffe_shop, local: true) do |form| %>
  <% if coffe_shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coffe_shop.errors.count, "error") %> prohibited this coffe_shop from being saved:</h2>

      <ul>
      <% coffe_shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

GofioScript/app/views/coffe_shops/edit.html.erb
<h1>Editing Coffe Shop</h1>

<%= render 'form', coffe_shop: @coffe_shop %>

<%= link_to 'Show', @coffe_shop %> |
<%= link_to 'Back', coffe_shops_path %>

GofioScript/app/views/coffe_shops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coffe Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coffe_shops.each do |coffe_shop| %>
      <tr>
        <td><%= coffe_shop.name %></td>
        <td><%= coffe_shop.description %></td>
        <td><%= coffe_shop.latitude %></td>
        <td><%= coffe_shop.longitude %></td>
        <td><%= link_to 'Show', coffe_shop %></td>
        <td><%= link_to 'Edit', edit_coffe_shop_path(coffe_shop) %></td>
        <td><%= link_to 'Destroy', coffe_shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coffe Shop', new_coffe_shop_path %>

GofioScript/app/views/coffe_shops/loadCoffeShopsFromCsv.erb
<h1>Finished</h1>

GofioScript/app/views/coffe_shops/new.html.erb
<h1>New Coffe Shop</h1>

<%= render 'form', coffe_shop: @coffe_shop %>

<%= link_to 'Back', coffe_shops_path %>

GofioScript/app/views/coffe_shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coffe_shop.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @coffe_shop.description %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @coffe_shop.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @coffe_shop.longitude %>
</p>

<%= link_to 'Edit', edit_coffe_shop_path(@coffe_shop) %> |
<%= link_to 'Back', coffe_shops_path %>